### PR TITLE
Moves from localstorage to indexeddb using level

### PR DESCRIPTION
**Pull request by AlbertoElias**
Main difference is that `create()` is now async which works nicely with orbitdb in the `libp2p` branch as you just need to add an `await` here: https://github.com/orbitdb/orbit-db/blob/libp2p/src/OrbitDB.js#L62

There are no tests, so I'm not sure how to try it out.

@aphelionz

### CODE REVIEW

**Comment by aphelionz** [comment]
@AlbertoElias Cool! What you'll need to do is clone the `orbit-db` repo and change the package.json to point to your branch. You can add that `await`, run the tests there, and then make a corresponding PR in orbit-db.

Mind that it might take a minute to get all the PRs merged since we're in the middle of preparing the 0.20 release, but we'll get to them!

**Comment by AlbertoElias** [comment]
@aphelionz I'm trying that but getting this error from an unrelated module:

```sh
/orbit-db/node_modules/pull-stream-to-async-iterator/index.js:4
  return (async function * () {
                         ^

SyntaxError: Unexpected token *
```

**Comment by AlbertoElias** [comment]
@aphelionz Okay, done fixing stuff. All good! Hope this makes it to the 0.20 release.

Here's the PR on orbit-db https://github.com/orbitdb/orbit-db/pull/580

**Comment by aphelionz** [comment]
@shamb0t This looks pretty good to me. What's your take? All tests pass in the corresponding orbit-db PR, though I'd want to merge this first so we're not pulling from @AlbertoElias's fork in the other repo.

**Comment by aphelionz** [comment]
Actually, I spoke too soon, looks like one `orbit-db` test is failing. Was this failing already? @AlbertoElias Can you reproduce this?

Screenshot_20190312_163343

**Comment by shamb0t** [comment]
@AlbertoElias thank you for the PR! This lgtm :+1:  @aphelionz I believe that failure is due to a race condition which should be fixed in next release, have you tried rerunning the tests?

**Comment by aphelionz** [comment]
@shamb0t Confirmed that the tests are fixed in the 0.20.x work in `orbit-db`

**Comment by shamb0t** [comment]
@aphelionz did you make any change other than adding `await` in `createInstance`?
I'm getting several leveldown errors `(node:9733) UnhandledPromiseRejectionWarning: OpenError: IO error: lock orbitdb/1/QmWnRAB1UsGaNbt6Ng1s2og65YQMCwnCW5cu1dbEjsPBXh/keystore/LOCK: already held by process`

**Comment by aphelionz** [comment]
In the orbit-db repo I ran:

```bash
$ git checkout AlbertoElias-update-keystore-indexeddb
$ git merge origin/feat/new-acs
$ rm -rf package-lock.json
$ make rebuild
```

**Comment by shamb0t** [comment]
Fixed after adding a call to `keystore.close()`. Happy to merge this now. Thank you @AlbertoElias :heart:

**Comment by AlbertoElias** [comment]
Yay! Thank you for your patience!

**Pull request merged**
