### PR TITLE
Fix/static verification

### PR DESCRIPTION
**Pull request by shamb0t**
This PR adds a static verify method and brings in changes from [fix/verification](https://github.com/orbitdb/orbit-db-keystore/tree/fix/verification) which includes:
- adding LRU cache
- error if arguments are missing
- removal of unused import/export methods
- add webpack config

### CODE REVIEW

**Comment by haadcode** [comment]
Looks good to me 👍 Note that this PR _doesn't_ add `LRU` as in the description (remnant of #7 I believe).

**Comment by haadcode** [comment]
Let's wait merging this until everything else has been bubbled upstream and tested for the new AC.

**Comment by shamb0t** [comment]
Woops you're right forgot to pull latest changes from fix/verification before branching. Shall I rebase?

**Comment by haadcode** [comment]
That would be good (assuming we need those changes).

**Pull request merged**
