### PR TITLE
feat: Implement generating keypair from seed

### PR DESCRIPTION
**Pull request by vaultec81**
# Background
Currently there is no ability to generate a keypair from a seed in a deterministic way. This PR adds the ability to pass `options.seed` to the `createKey` method.

## Use cases
For example a user friendly application where the user may be prompted to make a mnemonic backup of their private key seed prior to generating a keypair.

## Changes
* Adds new option `options.seed` & corresponding test
* Adds `cross-env` on test command

### CODE REVIEW

**Review by aphelionz — COMMENTED** [review]
Looking good. Does this just generate one keypair or two i.e. one for signing and one for encryption?

**Comment by vaultec81** [comment]
@aphelionz It only generates one keypair, same as before. I think a single secp256k1 keypair can be used for both encryption and signing.

**Comment by aphelionz** [comment]
It certainly _can_ but here's some [food for thought](https://security.stackexchange.com/questions/1806/why-should-one-not-use-the-same-asymmetric-key-for-encryption-as-they-do-for-sig)  Apologies for the SO link but the discussion there is fairly thorough and valuable. 

I'm very into this addition as I think it's a step toward our 1.0 roadmap but I want to make sure we're fairly rigorous about this since it's a deep, system-level feature, as well as an implicit recommendation that we'd be making to the community in terms of best practices

**Comment by vaultec81** [comment]
I am sure we can look into creating a specialized system for the encryption/decryption side of things. What is something to look into is bip39/bip44, which one of the features allows multiple private keys to be created from a single bip39 root key. Since this is in the same ball court, maybe a specialized system for requesting a new key from the bip39 seed for a specific purpose (like encryption/decryption) can be created?

**Comment by aphelionz** [comment]
That sounds compelling! I think what's important now is that we put something in that can be updated / changed easily later.

**Comment by vaultec81** [comment]
Considering this addition can be made now. A more specialized system with encryption of the secret can be made later which ultimately calls `createKey` with a seed unique to the key being requested. 

Flow: (Encrypted bip39 rootkey store) -> Decryption/authorization -> generation of child seed -> generation of keypair from child seed  (`createKey`) -> storage and tagging of keypair + child seed/unique tag used to create child seed from root key.

**Comment by aphelionz** [comment]
Thanks fro all that - tests are looking good! My next question is - Is this something we can utilize here? https://blog.bitjson.com/just-released-webassembly-version-of-secp256k1-10x-faster-than-javascript-eb3cebe4d411

**Comment by vaultec81** [comment]
For sure, we will have to look into further. Could improve write and oplog verification performance.

**Comment by aphelionz** [comment]
Yes, I do mean here though. That is - I'm curious to see if the wasm version gives the exact same output based on the seed - if it does I'd much prefer to use the more performant version in the browser and start making that a common practice.

**Comment by vaultec81** [comment]
It depends on the generation algorithm. From the elliptic source code i know it uses a PRNG of the seed input prior to generating the keypair. So most likely going to be a different algorithm. (I would of course have to find the source code docs on that to be 100% sure). Now as far as performance gain goes, it would be relatively small - only relevant during generation of the keypair. There would only be a performance gain if all the crypto was replaced in orbitdb.

**Comment by aphelionz** [comment]
Yes, that's all fairly correct. I'd like to do exactly that - replace all the crypto with wasm-compatible AND do the signature validation caching you mentioned as well, starting here. This is gonna get merged anyway at this point, but if we can stretch and land this here (where it's easy / somewhat low-impact as you say) then I'd call it a huge win :+1:

**Comment by aphelionz** [comment]
This is ready to merge. Locally, please:

1. Run `make rebuild` and commit in all the code in `dist/`, `package-lock.json` and anything else
2. Squash all the commits to one via `git rebase -i origin/master` and then force push to this branch

Then we're good to go!

**Pull request merged**
